### ISSUE TITLE
Base de données de RPG Maker 

### ISSUE THREAD

**Issue by Seusyn** [rpgmakeralliance/wiki#16]
Détails et différences entre les versions

**Comment by Seusyn** [comment]
Je le prends :)

**Comment by aureliendossantos** [comment]
Seusyn n'ayant pas donné de nouvelles depuis un long moment, vous pouvez prendre la main si vous le souhaitez 😉

**Comment by HuLijin** [comment]
Je sais que Monos et CuddleFox y bossent sur Oniro. Ça vaut sans doute el coup d'attendre que CuddleFox finisse son taf, j'en ai eu un aperçu et c'est de qualité.

**Comment by HuLijin** [comment]
Vieux sujet. Ça ne va aps faire double emploi avec la traduction @aureliendossantos ?

**Comment by aureliendossantos** [comment]
Si, tout à fait ! On pourra close quand y aura la doc.

**Comment by aureliendossantos** [comment]
Je ferme car ça fait doublon avec d'autres projets et les participant-e-s ont perdu en intérêt.
