### ISSUE TITLE
Page dédiée à RME

### ISSUE THREAD

**Issue by aureliendossantos** [rpgmakeralliance/wiki#27]

**Comment by aureliendossantos** [comment]
Différentes parties :
- Obtenir le script
- Découvrir : vidéo, wiki, tout ce qui peut servir au premier contact
- inventaire des features

**Comment by Jauke** [comment]
Sur discord: « Dernière version » me semble plus pertinent que « dernière publication », on parle bien de release, donc publication, mais c’est ce petit fil là qu’il vaut mieux mettre en avant plutot qu’un raw, qui, me semble-t-il, devra être mis à jour tout le temps

**Comment by aureliendossantos** [comment]
Le raw renvoie toujours vers la dernière version de la branche master, sans que le lien ait besoin d'être changé. J'ai justement déjà vu un membre de la team RME dire que ce lien serait utilisé pour partager le script un peu partout, il me semble. Par contre dans le cas d'ORMS ce lien n'est pas très clair ouais, puisque tu as besoin des fichiers image. Je viens de changer, qu'est-ce que t'en penses ?
https://wiki.rpgmakeralliance.com/scripts

**Comment by Jauke** [comment]
Ah oui, le raw prend la branche en source alors il n’y a pas de problème en effet... haha. La présentation de ORMS est nickelle, j’aurais pas fait mieux. :) gare « aux potentiel », c’est le seul petit détail qui m’a interpellé

**Comment by aureliendossantos** [comment]
Bien vu la faute, c'est corrigé ! Si ça t'intéresse, on est en train de refaire le wiki et il sera possible de l'éditer en markdown plutôt qu'en rst, ce qui permet de facilement copier-coller les readme. J'ai déjà fait ça avec la doc de certains scripts de Zeus pour essayer : 
https://wiki.rpgmakeralliance.com/scrollpictures
Après si tu préfères avoir le readme chez toi ça se comprend, mais si ça t'intéresse d'avoir une jolie page, sache que ça arrive très bientôt 🙂

**Comment by Jauke** [comment]
Nous sommes basés sur github pour l’instant mais, pour sûr, il est très agréable de voir notre travail rebasé en parallèle sur le wiki de RMA. :)

**Comment by aureliendossantos** [comment]
Ce sera du md uniquement. Je suis en train de convertir tout le contenu en md, pendant que Princesseuh s'occupe de la technique
