### ISSUE TITLE
Version anglaise du wiki

### ISSUE THREAD

**Issue by aureliendossantos** [rpgmakeralliance/wiki#90]
Tâches à réaliser avant de pouvoir sortir une première version publique du wiki en anglais.

- [ ] Implémentation du système multilingue #92 

Traductions intéressantes :

- [ ] Accueil du portail RPG Maker
   - [ ] Comparatif des versions
   - [ ] Installer un script
   - [ ] Liste des scripts
   - [ ] Script Fullscreen++
   - [ ] Script ORMS
- [x] Accueil du portail GameMaker
   - [x] Vue d'ensemble
   - [x] Tutoriels
- Portail Distribution
   - [x] Présenter son jeu
   - [x] Créer un site
   - [x] Kit de presse
- Portail Graphismes
   - [x] Principes
   - [x] Outils de création
- L'Encyclopédie
   - [ ] Contribuer
   - [ ] Syntaxe
   - [ ] Installer l'Encyclopédie
   - [x] Informations légales
- [x] Readme

**Comment by GoulvenC** [comment]
Cette issue est locked et taggé "Annulé" en attendant de savoir si on la recycle ou si on la close.

**Comment by aureliendossantos** [comment]
Closed car nous avons rendu plus modeste notre désir de conquête du monde. Tout le wiki ne sera pas traduit, seulement un Portail Anglophone #97
